module.exports = {
get_All_Bid:"Get all bids.",
AddBid:"Congratulation!!! Your bid has been placed.",
getAllCategory:"Get all categories.",
AunCat:"Add auction category successfully from admin.",
adminSuc:"Registered admin successfully.",
addAunction:"Congratulation!!! Your auction listed successfully. Please wait for people review.",
NOT_FOUND:"No data found.",
get_All_Aunc:"Get all auctions.",
userSuc:'User successfully registered.',
checkEmail:'Username already taken.',
ACCOUNT_STATUS :'Your account is deactivated by admin.',
chkFields      :'Please check all fields.',
LOGIN:'Login Successfully.',
LOGINUN:'Login Unsuccessfully.',
UPDATE_PROFILE:'Your profile has been updated. Please enjoy with new profile.',
CHKFIELD:'Please check all field.',
NODATA:'NO data found.',
NOEMAIL:"Username not exist.",
RESETPASS:"Reset password.",
FORGETPASS:"Please login next time with new password..",
NOT_RESPONDING: 'Please try after some time.',
GET_CAT: "Get all category..",
GET_PRO: "Get all product.",
NO_CAT: "Category not found.",
NO_PRO: "Product not found.",
GET_HISTORY: "Get chats history.",
getAllBrands: "Get all brands.",
getAllModels: "Get all models.",
NOTIFICATIONS:"Get all notifications.",
AddFAV:"Add favorite.",
UNFAV:"Remove favorite.",
GET_FAV:"Get all my favorites.",
AlreadyAdd:"Already favorite.",
NO_VALUE_SEND:"Please all fields.",
ADD_SUPP:"Support successfully added.",
GET_ALL_SUPP:"Get all supports successfully.",
GET_ALL_DATA:"Get all search data.",
BidDetails:"Bid already added.",
AddImage:"More images uploaded.",
NoImage:"NO image select.",
Incur:"Id is incorrect.",
updateAuc:"Auction information changed. Please wait for review. Thanks!!!",
deleteAuc:"Auction removed. Thanks",
NoChat:"No chat.",
base_url:"http://localhost/",
base_url_admin1:"http://localhost:3003/",
base_url_admin:"http://localhost:3004/assets/images/",
base_url_admin_for_image:"http://localhost/subasta_assets/images/",
update_rat:"Update Rating.",
AddRat:"Rating add successfully.",
getRat:"Get all rating.",
addSuc:"Added successfully.",
old:"old_password is incorrect.",
updateProfile:"Update profile.",
userDetails:"Get user details.",
addPackage:"Add package.",
getPackage:"Get all packages.",
buyPackage:"Add package successfully.",
GetAllSubsPackage:"Get all subscription packages.",
CurrHis:"Get all current subscriptions.",
MessageSent:"Sent message.",
AllMessages:"See all messages.",
SeeAllFriend:"See all friends.",
update_bid:"Update bid successfully.",
delete_bid:"Delete bid successfully.",
th_id:"Created thread_id.",
FORGETPASS1:"New password has been sent on your email.",
LOGIN_FLASH:"Your password is wrong.Please,enter correct password.",
message:"Congratulation your have started secure chat with your friend.",
addbidmessage:"Congrats, someone have interested on your product.",
BID_TYPE:"10003", //Place bid notification type
CHAT_TYPE:"10001",
ADMIN_NOTIFICATION_TYPE:"10004",
wonMessage:"GetRid",
winAuctionMessage:"Congratulation !!! you won the auction.",
winAuctionType:"10005",
block_user:"User is blocked.",
unBlock_user:"Unblock the user.",
beforeMessageType:'10006',
supportType:'10007'
};